# Generated by Django 5.1.4 on 2025-08-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0040_errorlotedetalle_commited_negativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLoteV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=30)),
                ('lote_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('commited', models.IntegerField(default=0)),
                ('error', models.CharField(max_length=200)),
                ('error_commited', models.BooleanField(default=False)),
                ('error_available', models.BooleanField(default=False)),
            ],
        ),
    ]
